### ISSUE TITLE
レーティング計算が間違っている

### ISSUE THREAD

**Issue by siman-man** [3w36zj6/atcoder-heuristic-rating-estimator#13]
https://www.dropbox.com/s/ne358pdixfafppm/AHC_rating.pdf?dl=0

AHC の公式ドキュメントの計算式では `r` を算出する際には `1 <= i <= 100` のはずですが、現状だと `0 <= i <= 99` で計算されています。

https://github.com/3w36zj6/atcoder-heuristic-rating-estimator/blob/cd6bf921d16f44051245170ca183f497e4a2ab60/src/App.svelte#L48-L51

**Comment by 3w36zj6** [comment]
ご報告ありがとうございます。修正しました。
